server:
  uploadPath:
spring:
  resources:
    static-locations: file:${server.uploadPath}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  datasource:
    url: jdbc:mysql://192.168.0.110:3306/fresh_shop?characterEncoding=UTF-8
    username: root
    password: Password123
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 2
    maxActive: 20
    maxWaitMillis: 8000
    dbcp2:
      default-auto-commit: false
  cache:
    type: redis
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1


role:
  rolename: 超级管理员
  rolecode: ROLE:ADMIN:SUPER
member:
  username: admin
  password: 123456
  phone: 13345678912

store:
  storename: 生鲜馆
  address: 长阳谷科技园
  tel: 13345678912
  about: 哈福生鲜
  businesslicenseno: 888888

brand:
  brandtitle: 无品牌
